- node/README.md
- node/api-client.js
- node/env0-deploy-cli.js
- node/env0-deploy-flow.js
- node/env0-deploy-utils.js
Adding `archiveAfterDestroy` option to CLI, so when we destroy our PR environments we can also archive them (after the destroy completes successfully)
> Adding archiveAfterDestroy option

- node/env0-deploy-flow.js
- node/env0-deploy-utils.js
API has changed since projects, and `projectId` is required to find all environments
> Fix: Use projectId instead of organizationId to find environments

- node/env0-deploy-cli.js
Passing an environment variable with empty string such as `FOO=` causes the CLI to fail on validation.  
This PR fixes that.
> Fix - Fail when using empty string env vars 

- node/yarn.lock
Updated dependencies due to the security issues we have in minimist and kind-of
> Chore: Update yarn.lock

- node/env0-deploy-cli.js
- node/env0-deploy-flow.js
- node/env0-deploy-utils.js
- node/tests/env0-deploy-cli.spec.js
- node/tests/env0-deploy-utils.spec.js
- node/yarn.lock
Currently all environment variables sent to CLI get `isSensitive: false` AKA we don't support sensitive environment variables in deployment
Besides the existing `-v` option for environment variables, I've added the `-vs` option that resembles that the passed key value variable should be marked as a sensitive environment variable.
> Feat: add sensitive variables support

- node/README.md
- node/env0-deploy-cli.js
- node/tests/env0-deploy-cli.spec.js
`command-line-args` package only supports aliases as one character, while sensitive environment variables where set to `-vs`
Changed it to `-q`
> Fix: sensitive environment variables alias

- node/env0-deploy-utils.js
Destroy API has been refactored in https://github.com/env0/env0/pull/1841 and should be updated in CLI.
> Chore: update destroy env api

- node/src/commons/config-manager.js
- node/tests/commons/config-manager.spec.js
When deployment finishes, we write the configuration to a file under the user's home folder.
If folder doesn't exist, `fs-extra`'s `writeJsonSync` throws.
change `fs-extra`'s `writeJsonSync` to `outputJsonSync`
> Fix: config manager doesn't create directory

- node/src/env0-deploy-cli.js
- node/tests/env0-deploy-cli.spec.js
After adding #27, there's a clash with `-v` for environment variables.
Remove `-v` for showing the version.
> Fix: CLI version command clash with env vars

- node/src/commons/arguments.js
- node/src/commons/config-manager.js
- node/src/commons/constants.js
- node/src/env0-deploy-cli.js
- node/src/env0-deploy-flow.js
- node/src/env0-deploy-utils.js
- node/tests/env0-deploy-flow.spec.js
- node/tests/env0-deploy-utils.spec.js
1. A user should be able to deploy/destroy an environment with some requires-approval flag.
2. A user should be able to approve an awaiting deployment from CLI.
3. A user should be able to cancel an awaiting deployment from CLI.
1. New `--requireApproval` (`-a`) argument.
2. New `env0 approve` command.
3. New `env0 cancel` command.
> Feat: require approval deployment + approve/cancel commands

- node/package.json
- node/src/commands/deploy.js
- node/src/commands/run-command.js
- node/src/config/arguments.js
- node/src/lib/config-manager.js
- node/src/lib/deploy-utils.js
- node/src/lib/logger.js
- node/src/main.js
- node/tests/lib/logger.spec.js
- node/tests/main.spec.js
- node/yarn.lock
We shouldn't log secrets.
1. Add a `winston` with a custom formatter that masks secrets like: `this-is-top-secret` -> `***************ecret`
2. Replace all `console` usage to use `logger` instead.
> Chore: add logger and hide secrets

- node/README.md
- node/jest.config.js
- node/package.json
- node/src/commands/cancel.js
- node/src/commands/configure.js
- node/src/commands/deploy.js
- node/src/commands/destroy.js
- node/src/commands/help.js
- node/src/commands/run-command.js
- node/src/config/arguments.js
- node/src/config/constants.js
- node/src/lib/deploy-utils.js
- node/src/lib/genetal-utils.js
- node/src/lib/set-deployment-approval-status.js
- node/src/main.js
- node/tests/commands/configure.spec.js
- node/tests/commands/deploy.spec.js
- node/tests/commands/destroy.spec.js
- node/tests/commands/run-command.spec.js
- node/tests/lib/deploy-utils.spec.js
- node/yarn.lock
1. On deploy - should not send an `undefined` requires approval value.
2. On destroy - updating requires approval before destroying was missing.
3. Revision overrides the environment's revisions due to its default value (master).
4. Requires approval argument was changed from `boolean` to `string` since not stating it should use previous value.
5. `env0 cancel` should not print logs.
1. Remove empty values on deploy.
2. Add that flow (similar to UI)
3. Remove the default value of revision.
4. Changed argument type.
5. Added a `shouldProcessDeploymentLogs` flag to deployment polling.
6. Fixed/Changed some problematic prints.
> Fix: final qa rejects

- node/src/commands/deploy.js
- node/src/commands/destroy.js
- node/src/config/arguments.js
- node/src/config/commands.js
- node/src/config/constants.js
- node/src/lib/deploy-utils.js
- node/tests/commands/deploy.spec.js
- node/tests/commands/destroy.spec.js
- node/tests/lib/deploy-utils.spec.js
A user should be able to use `terraform`'s `-target` parameter for applying his deployment on a partial set of the resources he had previously deployed (aka partial apply).
BE already supports the `targets` parameter for deploy and destroy APIs. Just passing it along 😺
> Feat: add partial apply support

- node/src/commands/help.js
- node/src/config/arguments.js
- node/src/config/commands.js
We wanted to have a better `env0 help` command
1. Added a link to the github repo.
2. Added link to env0 in the Banner.
3. Changed the option list to be per command.
4. Added examples to each command.
fixes https://github.com/env0/env0-client-integrations/issues/43
> chore: upgraded the help

- node/src/config/arguments.js
- node/src/main.js
- node/tests/main.spec.js
After #43 was merged, there are now `groups` of options per command, so we now need to extract the relevant arguments object of the command from the general arguments object that contains the groups.
As described.
> Fix: passing command options

- node/src/commands/deploy.js
- node/tests/commands/deploy.spec.js
We call `create environment` first (which doesn't assert blueprint ID) and then after that we call `deploy environment` (which asserts blueprint ID on initial deployment). This leads to a scenario that when a user forgets to include blueprint ID argument then environment is created but never deployed.
P.S - Our CLI flow works a little different than UI (we use `create environment` and only after that we `set configuration` + `deploy environment`). We should instead do `create environment` using `deployRequest` and `configurationChanges` in request body, but that's reserved for a different [task](https://github.com/env0/env0-client-integrations/issues/49).
In this PR I've introduced an assertion that takes place when environment doesn't exist (AKA initial deployment) and verifies that …
> Fix: assert blueprint id for initial deployment

- node/src/commands/deploy.js
- node/src/commands/destroy.js
- node/src/lib/deploy-utils.js
- node/src/lib/set-deployment-approval-status.js
- node/tests/commands/deploy.spec.js
- node/tests/commands/destroy.spec.js
- node/tests/lib/deploy-utils.spec.js
Support queued deployments.
1. Deploy/Destroy should not wait for environment status any longer.
2. Poll deployment should support `QUEUED` status by waiting for it to finish and printing proper logs.
> Feat: queued deployments

- node/src/commands/deploy.js
- node/tests/commands/deploy.spec.js
`configurationChanges` attribute in deploy request was missing the `scope` field.
Added `scope` field as `DEPLOYMENT`
> Fix: add missing scope in configuration changes

- node/src/lib/deploy-utils.js
- node/tests/lib/deploy-utils.spec.js
After adding API requets validation to env0 backend, the initial deployment request started failing due to unnecessary `organizationId` and `lifespanEndAt` parameters in body.
Remove `organizationId` and `lifespanEndAt` params from request body.
> Fix: initial deployment wrong arguments

- node/package.json
- node/yarn.lock
`yargs-parser` used by `jest` v24 has a security vulnerability.
Upgrade `jest` to v25.
> Chore: yargs-parser security vulenrability

- node/src/lib/deploy-utils.js
- node/tests/lib/deploy-utils.spec.js
Create API (aka first deploy) doesn't support the `requiresApproval` parameter.
Add it 😺
> Fix: support requires approval parameter in create api

- node/src/commands/run-command.js
- node/tests/commands/run-command.spec.js
Right now, we persist the flags we get in actions like deploy/destroy in our config file. We want to stop doing that
Stop doing that
> Fix: Persist configuration only in env0 configure

- node/src/main.js
- node/tests/commands/run-command.spec.js
- node/tests/main.spec.js
`deploy`,`destroy`,`cancel` and `approve` all fail because the flags were not sent to `commandLineArgs` when resolving the arguments
Send the args
> Fix: Most of the commands fail do to arguments not being resolved correctly

- node/src/main.js
- node/tests/main.spec.js
Our BE validation process returns axios `response.data` in the shape of an array of strings instead of the usual `{ message: string }` object.
Parse also the array's messages, if exists.
> Fix: log errors properly based on axios response 

- node/src/main.js
- node/tests/main.spec.js
After #70 was merged, it turns out there's also a case where `response.data` ia a string.
Treat that case.
> Fix: show better error messages #2

- node/src/lib/deploy-utils.js
Due to some caching issues with API Gateway, we reach limits from our 3rd-party authorization provider when using API keys on getting a step log's output. 
Temporary increase the find-step-logs API call interval.
> Chore: increase find step log api calls interval

- node/package.json
- node/src/commands/deploy.js
- node/tests/commands/deploy.spec.js
Redeploying with `-w` for workspace name assumes one's trying to **change** the workspace name of existing env.  
Instead - we should check that it has been changed and only then throw an error - otherwise - it should be allowed.
> Fix: Allow same workspace name on redeploy

- node/src/lib/deploy-utils.js
- node/tests/lib/deploy-utils.spec.js
We're getting `502` from env0 BE when trying to get all environments for a project. 
Use the `name` query param for the GET `/environments` API so filtering would be done by BE and not on client
> Chore: use name query param when getting environments

- node/src/commands/deploy.js
- node/tests/commands/deploy.spec.js
The CLI sends the scope variable to the api.
Remove the scope sent by the CLI.
> Fix: Don't send scope variable

- node/npm-shrinkwrap.json
- node/package.json
- node/yarn.lock
`colors` developer is crazy.
our cli could install the bad version of `colors` as a transitive dependency by `winston`.
upgrade "winston" 3.3.4 - in that version, they locked to the previous and safe version of `colors`
> fix transitive "colors" bad dependency

- node/README.md
- node/package.json
`npm publish` call isteslf
add publish section in README
remove publish script because it's causing a publishing loop
> chore: add publish section in README

- node/npm-shrinkwrap.json
- node/package.json
- node/yarn.lock
Fixes https://github.com/env0/env0-client-integrations/issues/109
`npm` versions > 15 fail to run the CLI tool
Reason: We run `npm shrinkwrap` in postinstall, which fails on global npm installations of the CLI package
Do no `npm shrinkwrap` in `postinstall`, it is updated anyway when doing `npm install` on recent `npm` versions
Also, ran `npm install`
> Do not run `npm shrinkwrap` postinstall

- node/src/lib/api-client.js
- node/tests/lib/api-client.spec.js
We're seeing an elevated rate of throttling errors as we do not benefit from cache when using user/password.  
Use user/password once to obtain JWT and use that on following API calls.
.
> Obtain JWT on client init

- node/npm-shrinkwrap.json
- node/package.json
- node/src/lib/api-client.js
- node/tests/lib/api-client.spec.js
Reverts env0/env0-client-integrations#112  
We've made it so that the env0 will properly use a short-term cache for user/password auth, so no need for each client to obtain a JWT first.
> Revert: Obtain JWT on client init

- .github/workflows/ci.yml
- node/npm-shrinkwrap.json
- node/package.json
https://github.com/env0/env0-client-integrations/pull/115 fails b/c the new dependency version needs at least node 14.
[node 10 is EOL](https://github.com/nodejs/release#end-of-life-releases) 
use node 14 - the oldest maintained LTS release
> Chore: use node 14

- .github/pr-labeler.yml
- .github/release.yml
- node/npm-shrinkwrap.json
- node/package.json
release version with security updates
- bump version
- auto label `prepare-release-*` branches
- exclude PRs with `prepare-release` label from release notes
> Prepare release v1.0.21

- .github/workflows/ci.yml
- node/.eslintrc
- node/npm-shrinkwrap.json
- node/package.json
- node/src/lib/update-notifier-utils.js
- node/src/main.js
- node/tests/main.spec.js
- node/yarn.lock
[Chore(deps): Bump got and update-notifier in /node (](https://github.com/env0/env0-client-integrations/pull/122/commits/1f86a70b38445abb2abcdd8bf55bd37279b1adeb)
^ new version of `update-notifier` is native ESM.
- extract this module usage to it's own file.
- exclude it from `eslint` check
- mock it in test
- run `cli --help` as naive integration test.
> Chore 3rd party upgrade fix
