env0/env0-client-integrations

.github/workflows/ci.yml
node/env0-deploy-utils.js
node/package-lock.json
node/tests/env0-deploy-utils.spec.js

That's been enforced by the endpoint now

Do not send projectId on configuration endpoint

---

node/yarn.lock

Security issue found.
https://snyk.io/vuln/SNYK-JS-MINIMIST-559764

Upgrade minimist to 1.2.2

---

node/yarn.lock

Based on this: https://app.snyk.io/vuln/SNYK-JS-ACORN-559469

bumped acorn version to 7.1.1

---

.github/pr-labeler.yml
.github/pull_request_template.md
.github/workflows/auto_assign.yml
.github/workflows/pr-auto-assign.yml
.github/workflows/pr-labeler.yml

Add:
1. PR template
2. Auto assign GH action
3. PR labeler GH action

Chore: add some github actions

---

node/package.json
node/src/env0-deploy-cli.js
node/yarn.lock

Chore: cooler env0 logo box

---

node/src/commons/config-manager.js
node/src/env0-deploy-flow.js
node/src/env0-deploy-utils.js
node/tests/env0-deploy-flow.spec.js
node/tests/env0-deploy-utils.spec.js

Deployment logs should be printed in CLI.
Poll the deployment steps API and GET log for each step.

Feat: stream deployment logs

---

node/.eslintrc
node/.prettierrc
node/README.md
node/package.json
node/src/commons/api-client.js
node/src/commons/arguments.js
node/src/commons/config-manager.js
node/src/commons/constants.js
node/src/env0-deploy-cli.js
node/src/env0-deploy-flow.js
node/src/env0-deploy-utils.js
node/tests/commons/api-client.spec.js
node/tests/commons/config-manager.spec.js
node/tests/env0-deploy-cli.spec.js
node/tests/env0-deploy-flow.spec.js
node/tests/env0-deploy-utils.spec.js
node/yarn.lock

Chore: add prettier

---

.github/workflows/ci.yml
node/.eslintrc
node/jest.config.js
node/package.json
node/tests/commons/config-manager.spec.js
node/tests/env0-deploy-cli.spec.js
node/tests/env0-deploy-flow.spec.js
node/tests/env0-deploy-utils.spec.js
node/yarn.lock

- Added missing `eslint-plugin-prettier` for eslint to run properly after adding prettier
- Added global jest config with proper mock reset.
- Added `lint` as a step in CI

Chore: add some configurations

---

node/.gitignore
node/README.md
node/bin/cli.js
node/index.js
node/package.json

- Better Readme
- Better `package.json`
- Move `index.js` into `bin/cli.js`

Chore: update readme

---

node/package.json

Chore: bump version to 1.0.2

---

node/package.json

bump version 1.0.3

---

node/README.md

Targets argument was missing in readme

Chore: add targets argument to README

---

node/package.json

Chore: bump version to 1.0.4

---

node/README.md
node/src/commands/deploy.js
node/src/config/arguments.js
node/src/config/constants.js
node/src/lib/deploy-utils.js
node/tests/commands/deploy.spec.js

Users should be able to set terraform workspace name.  
Add CLI parameter

Add workspace name parameter

---

node/README.md

Refactor readme.
1. npm version badge
2. npm downloads badge
3. license badge
4. set readme links

Chore: add badges to readme

---

node/package.json

Bump npm version to 1.0.7 that includes #55

Chore: bump version 1.0.7

---

node/jest.config.js
node/package.json
node/src/main.js
node/tests/main.spec.js
node/yarn.lock

Fixes #34 
Notify users that we have a new version.
Use [update-notifier](https://www.npmjs.com/package/update-notifier) package.
Example:

Feat: add update notifier

---

node/package.json

Chore: bump version 1.0.8

---

node/package.json

Chore: bump version 1.0.9

---

node/package.json

Bump version to 1.0.10
Bump version to 1.0.10

Chore: Bump version to 1.0.10

---

node/package.json

Chore: bump to version 1.0.11

---

node/package.json

Chore: bump version to v1.0.12

---

node/package.json

- We need to know how to publish this package
- Since it's a simple one liner I added it to the package.json scripts

Chore: Add publish script

---

node/package.json

Bump version to `1.0.14` after merging #94
☝️

Chore: bump version to 1.0.14

---

node/README.md
node/npm-shrinkwrap.json
node/src/commands/deploy.js
node/src/commands/help.js
node/src/commands/run-command.js
node/src/config/arguments.js
node/src/config/commands.js
node/src/config/constants.js
node/src/main.js
node/tests/commands/deploy.spec.js
node/tests/main.spec.js
node/yarn.lock

Add support for Terraform Variables
Need help deciding what variable option to use - currently using `-u` since `-t` is taken by targets.

feat: adding support for Terraform Variables

---

node/package.json

chore: bump version to 1.0.16

---

node/package.json

Bump version to 1.0.23
